name: Test

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@v1.0.2
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}